// @generated by experiments/compile_flash_manifest_v1.py
// Do not edit by hand. Runtime policy contains promoted capabilities only.

pub(crate) const DIRECT_VAR_EVAL: bool = true;
pub(crate) const DIRECT_FRAMED_PRUNE: bool = false;

pub(crate) const PROMOTED_CAPABILITY_IDS: &[&str] = &[
    "direct_var_eval",
];
